Add X11 libraries to Unix build linking flags
Add -lX11 -lXxf86vm -lXi to unix:LIBS in qt/pigale.pro to fix
linker errors when building with freeglut on Linux.

Fixes the error:
  /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libglut.a(fg_window_x11.c.o):
  undefined reference to symbol 'XGetWindowAttributes'
  /usr/bin/ld: /lib/x86_64-linux-gnu/libX11.so.6:
  error adding symbols: DSO missing from command line

These libraries are required by freeglut for X11 window management.